### ISSUE TITLE
More paste options please

### ISSUE THREAD

**Issue by sejtam** [benbasson/pastequote#1]
I'll  try and provide a contribution (need to pait for Paypal first). Anyway, I would loke to see a few more options for quoting pasted.

Currently you are providing:  [QUOTE].....paste content....[/QUOTE]
which is fine in may cases, but I have use (email via web interface etc) to also paste quotes that look like

> content line 1
> content line 2

and in some cases
| content line 1
| content line 2

So it would be really swell if your add-on could offer these too (as separate options in the right-click-menu). In fact I think the quote characters (>, | etc) should be user-settable, as should be an option for each whether the content of the clipboard should be rewrapped before pasting (both, wrapping single lines and keeping CR or ignoring CRs maybe?)

Additional chrome might be allowing the prefixing with current date/time (and similarly injecting that into the [QUOTE when=] ... [/QUOTE]  encapsulation. I am sure other modifications may also be possible,

My immediate need for this is that can quote like in email, and also distinguish quotes between 'previous email text' and 'quoted text from external source' (like an RFC or website).

If this then also worked in Thunderbird that would be fatastic.

thanks
Mathias

**Comment by benbasson** [comment]
Sorry, I'm very unlikely to maintain this add-on further. There are other options available, and with the move to WebExtensions in 2017, I am currently not considering spending time on an add-on that's only used by a couple of hundred people.
